### ISSUE TITLE
Regarding dataset access. 

### ISSUE THREAD

**Issue by Bala93** [DeepLearnXMU/QGC#1]
Can you make the contents in drive link public ?

**Comment by dingjingzhen** [comment]
@czwlines The same problem

**Comment by czwlines** [comment]
Sorry, I forgot to set access rights. It can be downloaded now!

**Comment by Bala93** [comment]
Thanks for the update. Could you also provide some information about the top 10 documents selection ? What dataset was used as a reference and which embedding was used ?

**Comment by czwlines** [comment]
We use Contriever to retrieve relevant documents from Wikipedia passages for both NQ and TQA datasets. For HQA, the raw data already includes the relevant documents.

**Comment by Bala93** [comment]
Thanks for your quick response

**Comment by Bala93** [comment]
For clarification, the order of the contexts is also ranked for all the datasets ? Looks like that when I check the code
https://github.com/DeepLearnXMU/QGC/blob/main/src/dataset.py#L220. Thanks.

**Comment by czwlines** [comment]
> For clarification, the order of the contexts is also ranked for all the datasets ? Looks like that when I check the code https://github.com/DeepLearnXMU/QGC/blob/main/src/dataset.py#L220. Thanks.

The contexts are already sorted in the file name containing `sorted`. In other files, the contexts remain unordered.

**Comment by Bala93** [comment]
When I was analyzing the dataset, I found that some of the contexts are relatively very large compared to the usual ones. For instance, average token length of the contexts is ~180, while some contexts are >1500. Why is this the case? And can we just remove them through truncate in tokenizer ?
